server:
  port: 8100
spring:
  application:
    name: order-service
  cloud:
    config:
      enabled: false


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true

logging:
  level:
    root: debug


